version: '3.7'

services:
  # service:
  #   build: .
  #   volumes:
  #     - .:/srv/service
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  db:
    image: mysql:5.7.30
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
